#!/usr/bin/env node
/**
 * Regenerates database.types.ts from the linked project and re-appends the
 * convenience aliases the workspace imports by name.
 *
 * The generator emits `Database['public']['Tables']['profiles']['Row']` and
 * nothing shorter, so without this step every regeneration would churn imports
 * across forty files.
 *
 * Usage: SUPABASE_ACCESS_TOKEN=... SUPABASE_PROJECT_REF=... node scripts/gen-types.mjs
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const ref = process.env.SUPABASE_PROJECT_REF;
if (!ref || !process.env.SUPABASE_ACCESS_TOKEN) {
  console.error('SUPABASE_ACCESS_TOKEN and SUPABASE_PROJECT_REF are required.');
  process.exit(1);
}

const generated = execFileSync(
  'npx',
  ['supabase', 'gen', 'types', 'typescript', '--project-id', ref, '--schema', 'public'],
  { encoding: 'utf8', maxBuffer: 32 * 1024 * 1024, shell: process.platform === 'win32' }
);

const ALIASES = `
// =============================================================================
// Convenience aliases
// =============================================================================
// Everything above is generated by \`npm run db:types\` and must not be edited by
// hand. This block is re-appended by scripts/gen-types.mjs and gives the
// workspace short, stable names for the shapes it uses most, so a regeneration
// never churns imports across the codebase.

// Tables / TablesInsert / TablesUpdate / Enums come from the generator itself;
// only Views is missing, so that is the one we add.
export type Views<T extends keyof Database['public']['Views']> =
  Database['public']['Views'][T]['Row'];

// --- Enums -------------------------------------------------------------------
export type UserRole = Enums<'user_role'>;
export type ArticleStatus = Enums<'article_status'>;
export type ReviewAction = Enums<'review_action'>;
export type MediaKind = Enums<'media_kind'>;
export type VideoProvider = Enums<'video_provider'>;
export type ContentLanguage = Enums<'content_language'>;
export type SubscriptionStatus = Enums<'subscription_status'>;
export type PlanInterval = Enums<'plan_interval'>;
export type PlanAudience = Enums<'plan_audience'>;
export type PaymentStatus = Enums<'payment_status'>;
export type EntitlementKind = Enums<'entitlement_kind'>;
export type NewsletterKind = Enums<'newsletter_kind'>;
export type EmailEventKind = Enums<'email_event_kind'>;
export type PushTopic = Enums<'push_topic'>;

// --- Table rows --------------------------------------------------------------
export type ProfileRow = Tables<'profiles'>;
export type OrganizationRow = Tables<'organizations'>;
export type CategoryRow = Tables<'categories'>;
export type LocationRow = Tables<'locations'>;
export type TagRow = Tables<'tags'>;
export type MediaRow = Tables<'media'>;
export type UploadTicketRow = Tables<'upload_tickets'>;
export type ArticleRow = Tables<'articles'>;
export type ArticleMediaRow = Tables<'article_media'>;
export type ArticleVideoRow = Tables<'article_videos'>;
export type ArticleRevisionRow = Tables<'article_revisions'>;
export type ArticleStatusHistoryRow = Tables<'article_status_history'>;
export type EditorReviewRow = Tables<'editor_reviews'>;
export type ArticleAssignmentRow = Tables<'article_assignments'>;
export type CommentRow = Tables<'comments'>;
export type SubscriptionPlanRow = Tables<'subscription_plans'>;
export type SubscriptionRow = Tables<'subscriptions'>;
export type PaymentRow = Tables<'payments'>;
export type EntitlementRow = Tables<'entitlements'>;
export type ContentLicenseRow = Tables<'content_licenses'>;
export type LicenseUsageRow = Tables<'license_usage'>;
export type NewsletterSubscriberRow = Tables<'newsletter_subscribers'>;
export type PushSubscriberRow = Tables<'push_subscribers'>;
export type AuditLogRow = Tables<'audit_logs'>;
export type SiteSettingsRow = Tables<'site_settings'>;
export type HomepageSectionRow = Tables<'homepage_sections'>;
export type NotificationRow = Tables<'notifications'>;

// --- View rows ---------------------------------------------------------------
export type ArticlePreviewRow = Views<'article_previews'>;
export type AuthorProfileRow = Views<'author_profiles'>;
export type TrendingArticleRow = Views<'trending_articles'>;
`;

writeFileSync('packages/database/src/generated/database.types.ts', generated + ALIASES, 'utf8');
console.log('database.types.ts regenerated');
